### ISSUE TITLE
GPS doesn't work when navigating

### ISSUE THREAD

**Issue by xangma** [evilexecutable/Lineage-17.0-Bugtracker#10]
Device: Galaxy Note 9
Description: I seem to have an issue with GPS when using navigation - the position doesn't move at all. GPS in maps works fine.

[Logcat here](https://gist.github.com/xangma/a2b667b92d5b28ed93ea2018bbe4057a)

**Comment by evilexecutable** [comment]
I can confirm I've been able to get a GPS lock. Hopefully my next release will have this sorted.

![IMG_20200121_144755](https://user-images.githubusercontent.com/6544968/72814785-8ccb9a00-3c5d-11ea-9217-de53dda01f10.jpg)

**Comment by evilexecutable** [comment]
It's also worth noting that I did test a walk up the street, too.

**Comment by xangma** [comment]
Woohoo! Thanks for the update, works perfectly :-)
