### ISSUE TITLE
[Note 9] [Microphone not working in apps]

### ISSUE THREAD

**Issue by lego-duck** [evilexecutable/Lineage-17.0-Bugtracker#2]
[logcat_12-20-2019_10-24-51.txt](https://github.com/evilexecutable/Lineage-17.0-Bugtracker/files/3987851/logcat_12-20-2019_10-24-51.txt)
Mic isn't working with Google assistant or voice recording apps.

Note 9
![Screenshot_20191219-222801_Logcat_Reader](https://user-images.githubusercontent.com/59069843/71215284-38747980-22af-11ea-9a4d-7205a943a0df.png)

**Comment by evilexecutable** [comment]
Hi, unfortunately for things like this, a screenshot won't do. I need you to run ```adb logcat -b all > logcat.txt``` on your computer while performing the broken task.

**Comment by evilexecutable** [comment]
Are regular calls okay?

**Comment by lego-duck** [comment]
> Are regular calls okay?

**Comment by lego-duck** [comment]
Yeah mic in calls seems to work ok
