### ISSUE TITLE
[Note 9] [Can't record video]

### ISSUE THREAD

**Issue by lego-duck** [evilexecutable/Lineage-17.0-Bugtracker#3]
[logcat_12-20-2019_10-19-47.txt](https://github.com/evilexecutable/Lineage-17.0-Bugtracker/files/3987833/logcat_12-20-2019_10-19-47.txt)
Camera apps can't record video it either lags or crashes

Tested with WhatsApp and Camera apps.
![Screenshot_20191220-081323_Logcat_Reader](https://user-images.githubusercontent.com/59069843/71240457-13a8f200-2301-11ea-9d1b-b8a9fc050d8b.png)

**Comment by evilexecutable** [comment]
Hi, unfortunately for things like this, a screenshot won't do. I need you to run ```adb logcat -b all > logcat.txt``` on your computer while performing the broken task.

**Comment by evilexecutable** [comment]
Will be fixed in the next Note 9 build.
