### ISSUE TITLE
[Note 9] [Play store apps slow to install or get stuck installing]

### ISSUE THREAD

**Issue by lego-duck** [evilexecutable/Lineage-17.0-Bugtracker#4]
[Logcat](https://drive.google.com/file/d/10Sbz488CODBqvGRXxs4LUmkuHqyC_FWu/view?usp=drivesdk) Sometimes apps get stuck at 100% downloaded other times apps take awhile to download. 
![Screenshot_20191220-081140_Logcat_Reader](https://user-images.githubusercontent.com/59069843/71240585-700c1180-2301-11ea-8a96-475a2161821f.png)
[logcat_12-20-2019_08-11-23.txt](https://github.com/evilexecutable/Lineage-17.0-Bugtracker/files/3987798/logcat_12-20-2019_08-11-23.txt)

**Comment by evilexecutable** [comment]
Hi, unfortunately for things like this, a screenshot won't do. I need you to run ```adb logcat -b all > logcat.txt``` on your computer while performing the broken task.

**Comment by evilexecutable** [comment]
Gapps issue. I find it happens if you still have the "set up your phone" notification. A reboot helps too.
