### ISSUE TITLE
Bluetooth Audio Issues during using Google or calls

### ISSUE THREAD

**Issue by Andrw0830** [evilexecutable/Lineage-17.0-Bugtracker#5]
TITLE: Bluetooth Audio Issues during using Google or calls

Description: 12/19/2019 starlte build

Device: starlte
Description of issue: If you are using Google or when making calls, audio playback sounds like chipmunks (really fast) and Audio from the Mic doesn't work
Logcat: 2 during tests of BT over car system and when using a BT Overear headset. Also 1 during using a BT Platronics headset.

**Comment by Andrw0830** [comment]
[logcat_bt-car_and_headset.txt](https://github.com/evilexecutable/Lineage-17.0-Bugtracker/files/3990785/logcat_bt-car_and_headset.txt)
[logcat_bt-Platronics.txt](https://github.com/evilexecutable/Lineage-17.0-Bugtracker/files/3990786/logcat_bt-Platronics.txt)

**Comment by Andrw0830** [comment]
- Used Google in Car at around 08:39 EST when discovered sound and recording issue
- Tried Google again around 16:45 and manually made a call when hearing call issue
- Used regular BT over-ear headset at 18:39-18:40 trying Google and Calls
- Used Platronics Headset at 18:49 - 18:50 trying Google and Calls

Let me know if you need anything else? Thanks for taking care of our device.

**Comment by evilexecutable** [comment]
This will be fixed in the next update. Thanks for the report!

**Comment by Andrw0830** [comment]
2019-12-23 S9 Update, still has either no BT audio being played back or the playback sounds like chipmunks through the speakers.

- around 11:55, received a call in the car and no audio through speakers (was someone else's car)
- came home and at around 12:35 tried calling my voicemail in my car and got chipmunk audio
- 12:39, did a test call on my Platronics BT Headset and no audio

**Comment by Andrw0830** [comment]
[logcat-2019-12-23.txt](https://github.com/evilexecutable/Lineage-17.0-Bugtracker/files/3995797/logcat-2019-12-23.txt)

**Comment by Andrw0830** [comment]
Issue resolved by latest LOS build.
