### ISSUE TITLE
[S9] [HEVC and VP9 hardware acceleration not working]

### ISSUE THREAD

**Issue by AnonymousUnavailable** [evilexecutable/Lineage-17.0-Bugtracker#6]
Device: Galaxy S9
Description of issue: Hardware acceleration for HEVC and VP9 is not working, but works fine with MPEG4. Tested on MX Player and VLC. Here are the screenshots.
![HEVC](https://user-images.githubusercontent.com/59112221/71306510-219f6580-241c-11ea-8907-3b7d71c425f3.png)
![VP9](https://user-images.githubusercontent.com/59112221/71306511-2401bf80-241c-11ea-985f-63cb39e9a862.png)
![MPEG4](https://user-images.githubusercontent.com/59112221/71306513-26641980-241c-11ea-9b01-8a5e6c0b9276.png)

**Comment by evilexecutable** [comment]
Hey, thanks for the report. This will be fixed in the next build. Keep an eye on the Telegram group for when it's released.
