### ISSUE TITLE
[S9] [HDR tone mapping works only in portrait mode]

### ISSUE THREAD

**Issue by AnonymousUnavailable** [evilexecutable/Lineage-17.0-Bugtracker#7]
Device: Galaxy S9
Description of issue: HDR tone mapping works in portrait mode but fails in landscape mode. This can be reproduced by playing HDR video files, encoded in HEVC or VP9, in stock Gallery, Google Photos, MX Player (with HW decoder) and some other players. HDR playback is normal in portrait mode, but in landscape mode, HDR tone mapping fails to work, resulting in washed out color.
However, on YouTube, HDR works correctly in both modes. On MX Player (with HW+ decoder or SW decoder) and VLC, HDR tone mapping fails to work in both modes.

**Comment by evilexecutable** [comment]
In /vendor/default.prop, can you add the following 2 lines:

> ro.surface_flinger.has_wide_color_display=true
> ro.surface_flinger.has_HDR_display=true

And then reboot. Let me know if that changes anything

**Comment by evilexecutable** [comment]
Hi, did you get chance to check the above?

Thanks.

**Comment by AnonymousUnavailable** [comment]
HDR tone mapping works normally after adding those 2 lines.
