### ISSUE TITLE
Wifi Mac Address 

### ISSUE THREAD

**Issue by nosar77** [evilexecutable/Lineage-17.0-Bugtracker#8]
After every reboot the WiFi Mac Address changes which causes an issue for getting IP's via DHCP and for apps that use the WIFI Mac Address as DRM (Gcam)

**Comment by evilexecutable** [comment]
If an app uses a Mac address as DRM and can't tell when it's being spoofed, it's not a very good app.

Stop using shitty cracked apps.

**Comment by nosar77** [comment]
> If an app uses a Mac address as DRM and can't tell when it's being spoofed, it's not a very good app.
> 
> Stop using shitty cracked apps.

Gcam isnt a cracked app, Google Cam is free. Do you seriously not know about this? lol

**Comment by evilexecutable** [comment]
Gcam is a proprietary Google app designed for the Pixel/Nexus line. Sorry, you're right, it's "ported".

Stop using shitty DRM apps. And by shitty, I mean the DRM its self, not the app.

**Comment by nosar77** [comment]
yeah luckily the DRM is removed so it doesnt use a MAC address. so its not a problem anymore. And  not necessarily you can download GCam on almost any phone. the newer versions only work on the pixel/nexus line by you can doing gcam on my S9 even on stock TW
